name: Deploy Site on Repo Creation

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --env OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} --prod --yes --token $VERCEL_TOKEN --scope hadadadebadada
          


#SERPAPI_API_KEY=${{ secrets.SERPAPI_API_KEY }} --token $VERCEL_TOKEN
