name: Deploy Site on Repo Creation

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # or your preferred version

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          yes | vercel --prod -t $VERCEL_TOKEN --scope hadadadebadada --name test
          vercel env add SUPABASE_URL "${{ secrets.SUPABASE_URL }}" --token $VERCEL_TOKEN
          vercel env add SUPABASE_SECRET "${{ secrets.SUPABASE_SECRET }}" --token $VERCEL_TOKEN
          vercel env add OPENAI_API_KEY "${{ secrets.OPENAI_API_KEY }}" --token $VERCEL_TOKEN
          vercel env add SUPABASE_PRIVATE_KEY "${{ secrets.SUPABASE_PRIVATE_KEY }}" --token $VERCEL_TOKEN
          vercel --token $VERCEL_TOKEN --prod --yes

          

         # vercel env add [name] [environment] [gitbranch] < [file]
