name: Deploy Site on Repo Creation

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --yes --token $VERCEL_TOKEN --scope hadadadebadada
          
      - name: Set environment variables on Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel env add SUPABASE_URL "${{ secrets.SUPABASE_URL }}" production --token $VERCEL_TOKEN
          vercel env add SUPABASE_SECRET "${{ secrets.SUPABASE_SECRET }}" production --token $VERCEL_TOKEN
          vercel env add OPENAI_API_KEY "${{ secrets.OPENAI_API_KEY }}" production --token $VERCEL_TOKEN
          vercel env add SUPABASE_PRIVATE_KEY "${{ secrets.SUPABASE_PRIVATE_KEY }}" production --token $VERCEL_TOKEN
