name: Deploy Site on Repo Creation

on:
  push: ##trigger sollte das hinzufügen von secrets über gh-api sein
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Delay for 1:30 minute
        run: sleep 90
      # the following steps will run after the delay
      - name: Next Step
        run: echo "This runs after the delay."

  
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --yes --token $VERCEL_TOKEN --scope hadadadebadada \
            --env SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --env SERPAPI_API_KEY=${{ secrets.SERPAPI_API_KEY }} \
            --env OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --env SUPABASE_PRIVATE_KEY=${{ secrets.SUPABASE_PRIVATE_KEY }}


        #evtl noch vercel link notwendig

          


