name: Deploy Site on Repo Creation

on:
  workflow_dispatch:
    inputs:
      chatBotId:
        description: 'ChatBot ID'
        required: true
      backendId:
        description: 'Backend ID'
        required: true
      name:
        description: 'ChatBot Name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel --prod --yes --token $VERCEL_TOKEN --scope hadadadebadada \
            --env SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --env SERPAPI_API_KEY=${{ secrets.SERPAPI_API_KEY }} \
            --env OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --env SUPABASE_PRIVATE_KEY=${{ secrets.SUPABASE_PRIVATE_KEY }}



          


